<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit Form</name>
   <tag></tag>
   <elementGuidId>aaaaf535-038a-40c4-a7e2-ab627ed5a1f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ff-btn.ff-btn-submit.ff-btn-md.ff_btn_style</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7373f4d-ceba-4358-8a1b-728c2e340c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>04b11799-5b3c-4463-bf36-2527ddd4823c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-btn ff-btn-submit ff-btn-md ff_btn_style</value>
      <webElementGuid>0ca9db98-e77f-4664-acdb-cb70458fb30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Form</value>
      <webElementGuid>ad55d2ff-c1ee-40f1-b424-cab61957dfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fluentform_3&quot;)/div[@class=&quot;ff-el-group ff-text-left ff_submit_btn_wrapper&quot;]/button[@class=&quot;ff-btn ff-btn-submit ff-btn-md ff_btn_style&quot;]</value>
      <webElementGuid>d533efe4-85d1-43d5-a995-e2fe3dd328a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>38870612-cdc0-4495-a07c-7c730a01b91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_3']/div[6]/button</value>
      <webElementGuid>2eef7dcb-adc2-4c93-acf3-e88e8b8e0e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Message'])[1]/following::button[1]</value>
      <webElementGuid>3585b3c7-47f0-4528-a5ca-f4e1ec86968e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Select one service -'])[2]/following::button[1]</value>
      <webElementGuid>85e0e82c-8366-4ab4-8acb-989cb1eed6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[2]/preceding::button[1]</value>
      <webElementGuid>dc79490a-4ef5-4f3f-ab78-b52e34a921ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[2]/preceding::button[1]</value>
      <webElementGuid>952d7978-9fca-4c8f-8c1b-94fb8c5dd0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit Form']/parent::*</value>
      <webElementGuid>764e7eb7-f7d8-42ba-8294-2be9cde66ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>dbcb9add-f89c-418a-a3e4-5cb037d11401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Submit Form' or . = 'Submit Form')]</value>
      <webElementGuid>58db5873-6fd7-4011-acde-c3043976cf62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
