<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContactUS_listbox_Apps and Cloud</name>
   <tag></tag>
   <elementGuidId>85c001c1-b595-4a6a-8488-3b66a2bc562f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-ff_3_dropdown-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-ff_3_dropdown-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8bbb1c6b-1318-4a73-b838-8862ceb76c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>48f7ccad-33e4-4d34-8c8a-cecf4f3023ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ff_3_dropdown-container</value>
      <webElementGuid>00dee1e5-dad0-4af7-91c4-ec1a1983d9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Apps and Cloud</value>
      <webElementGuid>ae8dbb5e-634b-4c45-9950-b032920d42d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apps and Cloud</value>
      <webElementGuid>2c0bb76e-2446-44ef-b5d8-88bb50ce1949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ff_3_dropdown-container&quot;)</value>
      <webElementGuid>cfcd6546-b176-468f-945a-9292f7cb0244</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-ff_3_dropdown-container']</value>
      <webElementGuid>b01d9085-b4f8-45b0-87a6-6c04e85dea10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_3']/div[4]/div[2]/div/span/span/span/span</value>
      <webElementGuid>00f6abd4-cbb3-4615-89bd-e604c8771bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services'])[1]/following::span[4]</value>
      <webElementGuid>ec5840ae-3a34-4f73-bc05-bbe916958b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::span[4]</value>
      <webElementGuid>f5cdef1b-2ab4-4c6a-9a34-3e3d370f8709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Message'])[1]/preceding::span[3]</value>
      <webElementGuid>6b8d4ccb-c9f1-400e-a06c-8ed6f2bd863c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Form'])[1]/preceding::span[3]</value>
      <webElementGuid>dc670323-d3e7-4258-b9c8-ad35264fd695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>181d1bf0-7ffe-41b4-a537-b3761eba9d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-ff_3_dropdown-container' and @title = 'Apps and Cloud' and (text() = 'Apps and Cloud' or . = 'Apps and Cloud')]</value>
      <webElementGuid>884abe3b-3f0f-4ad7-93c8-13192c15a75c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
