<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContactUS_dropdown_Service</name>
   <tag></tag>
   <elementGuidId>56ec041f-867b-4eb3-947d-e8cd5bcc103c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-ff_3_dropdown-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-ff_3_dropdown-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a5d17639-68b8-4b81-88f7-ae3ac3e3d3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>44993964-ffff-4aee-ad33-808278d9d28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ff_3_dropdown-container</value>
      <webElementGuid>328174ac-afda-4f83-8112-89b68c3e06d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>- Select one service -</value>
      <webElementGuid>d940f22c-3c0c-43ac-a99b-8a978da47b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select one service -</value>
      <webElementGuid>12c49f78-22e2-4e38-9f31-8de4342b6c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ff_3_dropdown-container&quot;)</value>
      <webElementGuid>cf6e34e0-b570-4b4c-98c8-1460d240531f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-ff_3_dropdown-container']</value>
      <webElementGuid>d1487627-2854-4a5e-aad1-665c5723e390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_3']/div[4]/div[2]/div/span/span/span/span</value>
      <webElementGuid>1fe3a99b-0d46-4c66-b29f-eedccfa27641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services'])[1]/following::span[4]</value>
      <webElementGuid>728c6ac3-10aa-4632-9eaf-b657ce3799d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::span[4]</value>
      <webElementGuid>2056c6cb-eeab-4c55-a10b-8165d6c3f844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Message'])[1]/preceding::span[3]</value>
      <webElementGuid>30f89864-4441-4d9f-8f9b-56953b265cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Form'])[1]/preceding::span[3]</value>
      <webElementGuid>d232b26b-7221-453d-9860-d00f33f56091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>d21625e1-33ed-4e3d-815a-b1b9ea64f944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-ff_3_dropdown-container' and @title = '- Select one service -' and (text() = '- Select one service -' or . = '- Select one service -')]</value>
      <webElementGuid>46f8e928-036c-4314-b52f-3102b1e8a8ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
