<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verifikasi_ContactUs Berhasil</name>
   <tag></tag>
   <elementGuidId>100d5b27-2a0f-454e-9076-c40c9d4c6574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fluentform_3_success']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fluentform_3_success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9cd9c318-e909-4191-a9fd-2f50b7e2d512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fluentform_3_success</value>
      <webElementGuid>3ce66290-9772-44b1-af4d-676f9301883a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-message-success</value>
      <webElementGuid>ceded33e-8581-49da-a0d9-50403f5807ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for your message. We will get in touch with you shortly</value>
      <webElementGuid>4d5c470f-6f80-4b49-a5a4-ddf3d6a4d08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fluentform_3_success&quot;)</value>
      <webElementGuid>3eff7281-8bff-4414-9e15-929fe9ed7f62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='fluentform_3_success']</value>
      <webElementGuid>575e9ff8-08a8-4a55-b856-b6df9286807b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-contact-us']/div/div/div/div</value>
      <webElementGuid>09d04b93-fe1d-4789-9b29-37edfe726559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Form'])[1]/following::div[1]</value>
      <webElementGuid>0e930518-5e82-4f37-bd4d-e57fbfca224b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Message'])[1]/following::div[3]</value>
      <webElementGuid>5bfa7f87-dca5-4751-b899-9d230e6734df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[2]/preceding::div[2]</value>
      <webElementGuid>d28eb72c-f9e4-4e89-b024-8223a96270da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[2]/preceding::div[6]</value>
      <webElementGuid>1fb158f4-14d8-4af1-80da-b2d504a1c0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you for your message. We will get in touch with you shortly']/parent::*</value>
      <webElementGuid>7e52a219-714b-44dd-a212-4325fc19a336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>035856fa-ab6a-476c-82d6-3e564be297cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'fluentform_3_success' and (text() = 'Thank you for your message. We will get in touch with you shortly' or . = 'Thank you for your message. We will get in touch with you shortly')]</value>
      <webElementGuid>13cecf19-877d-4c6d-822b-9cecb8e96afb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
